/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface T {
  'name' : string,
  'createdAt' : bigint,
  'sellingPrice' : number,
  'frameNumber' : string,
  'quantity' : bigint,
  'brand' : string,
  'costPrice' : number,
}
export interface T__1 {
  'id' : string,
  'gst' : number,
  'customerName' : string,
  'createdAt' : bigint,
  'mobileNumber' : string,
  'grandTotal' : number,
  'frameNumber' : string,
  'framePrice' : number,
  'profit' : number,
  'lensPrice' : number,
  'rightEye' : T__2,
  'leftEye' : T__2,
}
export interface T__2 {
  'axis' : bigint,
  'addition' : number,
  'cylinder' : number,
  'sphere' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFrame' : ActorMethod<[T], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInvoice' : ActorMethod<[T__1], T__1>,
  'deleteFrame' : ActorMethod<[string], undefined>,
  'deleteInvoice' : ActorMethod<[string], undefined>,
  'getAllFrames' : ActorMethod<[], Array<T>>,
  'getAllInvoices' : ActorMethod<[], Array<T__1>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailySales' : ActorMethod<
    [string],
    { 'totalProfit' : number, 'totalSales' : number }
  >,
  'getFrame' : ActorMethod<[string], T>,
  'getInvoice' : ActorMethod<[string], T__1>,
  'getMonthlySales' : ActorMethod<
    [bigint, bigint],
    { 'totalProfit' : number, 'totalSales' : number }
  >,
  'getSalesSummary' : ActorMethod<
    [],
    {
      'invoiceCount' : bigint,
      'todayProfit' : number,
      'monthProfit' : number,
      'todayTotal' : number,
      'monthTotal' : number,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFrame' : ActorMethod<[string, T], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];