/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const T = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'sellingPrice' : IDL.Float64,
  'frameNumber' : IDL.Text,
  'quantity' : IDL.Nat,
  'brand' : IDL.Text,
  'costPrice' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const T__2 = IDL.Record({
  'axis' : IDL.Int,
  'addition' : IDL.Float64,
  'cylinder' : IDL.Float64,
  'sphere' : IDL.Float64,
});
export const T__1 = IDL.Record({
  'id' : IDL.Text,
  'gst' : IDL.Float64,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'mobileNumber' : IDL.Text,
  'grandTotal' : IDL.Float64,
  'frameNumber' : IDL.Text,
  'framePrice' : IDL.Float64,
  'profit' : IDL.Float64,
  'lensPrice' : IDL.Float64,
  'rightEye' : T__2,
  'leftEye' : T__2,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFrame' : IDL.Func([T], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInvoice' : IDL.Func([T__1], [T__1], []),
  'deleteFrame' : IDL.Func([IDL.Text], [], []),
  'deleteInvoice' : IDL.Func([IDL.Text], [], []),
  'getAllFrames' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailySales' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'totalProfit' : IDL.Float64, 'totalSales' : IDL.Float64 })],
      ['query'],
    ),
  'getFrame' : IDL.Func([IDL.Text], [T], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [T__1], ['query']),
  'getMonthlySales' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Record({ 'totalProfit' : IDL.Float64, 'totalSales' : IDL.Float64 })],
      ['query'],
    ),
  'getSalesSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'invoiceCount' : IDL.Nat,
          'todayProfit' : IDL.Float64,
          'monthProfit' : IDL.Float64,
          'todayTotal' : IDL.Float64,
          'monthTotal' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFrame' : IDL.Func([IDL.Text, T], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const T = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'sellingPrice' : IDL.Float64,
    'frameNumber' : IDL.Text,
    'quantity' : IDL.Nat,
    'brand' : IDL.Text,
    'costPrice' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const T__2 = IDL.Record({
    'axis' : IDL.Int,
    'addition' : IDL.Float64,
    'cylinder' : IDL.Float64,
    'sphere' : IDL.Float64,
  });
  const T__1 = IDL.Record({
    'id' : IDL.Text,
    'gst' : IDL.Float64,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'mobileNumber' : IDL.Text,
    'grandTotal' : IDL.Float64,
    'frameNumber' : IDL.Text,
    'framePrice' : IDL.Float64,
    'profit' : IDL.Float64,
    'lensPrice' : IDL.Float64,
    'rightEye' : T__2,
    'leftEye' : T__2,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFrame' : IDL.Func([T], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInvoice' : IDL.Func([T__1], [T__1], []),
    'deleteFrame' : IDL.Func([IDL.Text], [], []),
    'deleteInvoice' : IDL.Func([IDL.Text], [], []),
    'getAllFrames' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailySales' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalProfit' : IDL.Float64,
            'totalSales' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getFrame' : IDL.Func([IDL.Text], [T], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [T__1], ['query']),
    'getMonthlySales' : IDL.Func(
        [IDL.Int, IDL.Int],
        [
          IDL.Record({
            'totalProfit' : IDL.Float64,
            'totalSales' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getSalesSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'invoiceCount' : IDL.Nat,
            'todayProfit' : IDL.Float64,
            'monthProfit' : IDL.Float64,
            'todayTotal' : IDL.Float64,
            'monthTotal' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFrame' : IDL.Func([IDL.Text, T], [], []),
  });
};

export const init = ({ IDL }) => { return []; };